In [61]:
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime
from sqlalchemy.orm import sessionmaker, declarative_base
from datetime import datetime
from sqlalchemy.dialects.postgresql import ARRAY
from postgre_cred import database_url
import json
import random
import pandas as pd

In [2]:
resp = requests.get('https://api.zoommer.ge/v1/Content/mega-menu')

In [3]:
categories = resp.json()

In [118]:
# categories[0]

In [54]:
seen_ids = set()
seen_cats = set()
all_cats = []
for main_category in categories:
    for cat in main_category['childItems']:
        parent_cat_name = main_category['name']
        cat_name = cat['name']
        cat_id = cat['categoryId']
        if not cat_id or cat_id in seen_ids:
            continue
        if cat_name in seen_cats:
            cat_name = f'{parent_cat_name}_{cat_name}'
        seen_ids.add(cat_id)
        seen_cats.add(cat_name)
        all_cats.append([parent_cat_name, cat_name, cat_id])

In [56]:
categories_cleaned = []
for parent_cat_name, cat_name, cat_id in all_cats:
    parent_cat_name = parent_cat_name.strip().lower().replace(' | ', '_').replace('\'', '').replace(' ', '_').replace('-', '_').replace('მონიტორები', 'monitors')
    cat_name = cat_name.strip().lower().replace(' | ', '_').replace('\'', '').replace(' ', '_').replace('-', '_').replace('მონიტორები', 'monitors')
    # if cat_name == 'type':
    #     cat_name = 'laptop_type'
    categories_cleaned.append((parent_cat_name, cat_name, cat_id))
categories_cleaned

[('mobile_phones', 'mobile_brands', 855),
 ('mobile_phones', 'headsets_buds', 887),
 ('mobile_phones', 'smart_watch', 873),
 ('mobile_phones', 'accessories_for_mobile', 538),
 ('tabs', 'tabs', 877),
 ('tabs', 'smart_keyboard_pen', 1088),
 ('tabs', 'graphics_drawing_tablet', 776),
 ('tabs', 'e_book', 1086),
 ('tabs', 'tab_accessories', 539),
 ('tabs', 'headphones', 533),
 ('tabs', 'cables', 1145),
 ('it_laptops', 'brands', 717),
 ('it_laptops', 'type', 531),
 ('it_laptops', 'memory_carriers', 519),
 ('it_laptops', 'accessories', 700),
 ('it_laptops', 'office_equipment', 460),
 ('it_laptops', 'projectors', 642),
 ('smart_gadgets', 'living_room', 501),
 ('smart_gadgets', 'home_care', 500),
 ('smart_gadgets', 'kitchen', 495),
 ('smart_gadgets', 'self_care', 490),
 ('smart_gadgets', 'monitoring', 488),
 ('smart_gadgets', 'smart_relocation', 1164),
 ('smart_gadgets', 'outdoor', 1156),
 ('smart_gadgets', 'sport', 1169),
 ('smart_gadgets', 'pets', 469),
 ('smart_gadgets', 'smart_lighting', 1178),
 ('smart_gadgets', 'tools', 473),
 ('audio_systems', 'audio_systems_brands', 528),
 ('audio_systems', 'acoustic_systems', 532),
 ('audio_systems', 'top_audio', 740),
 ('audio_systems', 'microphones', 862),
 ('gaming', 'playstation', 688),
 ('gaming', 'xbox', 683),
 ('gaming', 'nintendo', 927),
 ('gaming', 'other_consoles', 1027),
 ('gaming', 'gaming_laptops', 675),
 ('gaming', 'gaming_accessories', 893),
 ('gaming', 'gaming_monitors', 1140),
 ('tv_monitors', 'tvs', 505),
 ('tv_monitors', 'all_in_one', 706),
 ('tv_monitors', 'monitors', 503),
 ('tv_monitors', 'tv_monitors_accessories', 506),
 ('tv_monitors', 'media_players', 891),
 ('photo_video', 'photography', 858),
 ('photo_video', 'optics', 462),
 ('photo_video', 'photo_video_accessories', 732),
 ('photo_video', 'drones', 865),
 ('photo_video', 'action_cameras', 864),
 ('photo_video', 'photo_printers', 881),
 ('photo_video', 'smartphone_photography', 1151)]

In [59]:
resp = resp.json()

In [119]:
# resp

In [65]:
df = pd.DataFrame(resp['products'])

In [127]:
df

,id,name,barCode,description,sellType,maxQuantityInCart,price,previousPrice,categoryId,doNotRecordStock,...,iconUrl,routeIsNotValid,subCategoryName,manualsFileUrl,certificateFileUrl,productFrame,productFrameResponsive,productDetailsFrame,productHorizontalFrame,productHorizontalFrameResponsive
0,45066,Apple MacBook Air 13 inch 2022 MC7U4LL/A M2 Ch...,ZOOM-035045,None,None,5,2999,NaN,531,False,...,None,None,None,None,None,None,None,None,None,None
1,19941,Apple MacBook Air 13 inch 2022 MLXW3LL/A M2 Ch...,ZOOM-028544,None,None,3,2599,3099.0,531,False,...,None,None,None,None,None,None,None,None,None,None
2,46331,Apple MacBook Air 13 inch 2022 MC7X4B/A M2 Chi...,ZOOM-035776,None,None,4,2999,NaN,531,False,...,None,None,None,None,None,None,None,None,None,None
3,46330,Apple MacBook Air 13 inch 2022 MC7U4B/A M2 Chi...,ZOOM-035775,None,None,11,2999,NaN,531,False,...,None,None,None,None,None,None,None,None,None,None
4,46246,Acer Aspire Lite 16 AL16-51P-570D NX.KWZER.001...,ZOOM-035737,None,None,3,1449,NaN,531,False,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,27995,Apple MacBook Air 13 inch 2022 MLXY3LL/A M2 Ch...,ZOOM-027574,None,None,3,2599,3099.0,531,False,...,None,None,None,None,None,None,None,None,None,None
249,23327,"Asus TUF 15 FA507NU-LP031, AMD Ryzen 7 7735HS,...",ZOOM-030250,None,None,16,3399,3599.0,463,False,...,None,None,None,None,None,None,None,None,None,None
250,22910,"Lenovo IdeaPad 3 82RK00QNRK, Intel Core i3-121...",ZOOM-029899,None,None,9,1129,NaN,531,False,...,None,None,None,None,None,None,None,None,None,None
251,20376,"HP Omen 16 78V44EA, AMD Ryzen 7-6800H Octa 4.7...",ZOOM-028888,None,None,1,4499,4999.0,713,False,...,None,None,None,None,None,None,None,None,None,None
252,20202,MSI Vector GP76 9S7-17K522-251 Black,ZOOM-028739,None,None,1,11199,11299.0,463,False,...,None,None,None,None,None,None,None,None,None,None

In [97]:
df_cl = df[['name', 'price', 'previousPrice', 'imageUrl', 'route']]

In [94]:
df_cl.head()

,name,price,previousPrice,imageUrl,route
0,Apple MacBook Air 13 inch 2022 MC7U4LL/A M2 Ch...,2999,NaN,https://s3.zoommer.ge/zoommer-images/thumbs/01...,laptops/apple-macbook-air-13-inch-2022-mc7u4ll...
1,Apple MacBook Air 13 inch 2022 MLXW3LL/A M2 Ch...,2599,3099.0,https://s3.zoommer.ge/zoommer-images/thumbs/01...,laptops/apple-macbook-air-13-inch-2022-mlxw3ll...
2,Apple MacBook Air 13 inch 2022 MC7X4B/A M2 Chi...,2999,NaN,https://s3.zoommer.ge/site/d79643b0-717a-4d86-...,laptops/apple-macbook-air-13-inch-2022-mc7x4b-...
3,Apple MacBook Air 13 inch 2022 MC7U4B/A M2 Chi...,2999,NaN,https://s3.zoommer.ge/site/3cc82a2e-5c27-467d-...,laptops/apple-macbook-air-13-inch-2022-mc7u4b-...
4,Acer Aspire Lite 16 AL16-51P-570D NX.KWZER.001...,1449,NaN,https://s3.zoommer.ge/site/bb3d7c79-8a0c-437b-...,laptops/acer-aspire-lite-16-al16-51p-570d-nx-k...

In [98]:
df_cl.loc[:, 'route'] = df_cl['route'].apply(lambda x: f'https://zoommer.ge/{x}')
df_cl.head()

,name,price,previousPrice,imageUrl,route
0,Apple MacBook Air 13 inch 2022 MC7U4LL/A M2 Ch...,2999,NaN,https://s3.zoommer.ge/zoommer-images/thumbs/01...,https://zoommer.ge/laptops/apple-macbook-air-1...
1,Apple MacBook Air 13 inch 2022 MLXW3LL/A M2 Ch...,2599,3099.0,https://s3.zoommer.ge/zoommer-images/thumbs/01...,https://zoommer.ge/laptops/apple-macbook-air-1...
2,Apple MacBook Air 13 inch 2022 MC7X4B/A M2 Chi...,2999,NaN,https://s3.zoommer.ge/site/d79643b0-717a-4d86-...,https://zoommer.ge/laptops/apple-macbook-air-1...
3,Apple MacBook Air 13 inch 2022 MC7U4B/A M2 Chi...,2999,NaN,https://s3.zoommer.ge/site/3cc82a2e-5c27-467d-...,https://zoommer.ge/laptops/apple-macbook-air-1...
4,Acer Aspire Lite 16 AL16-51P-570D NX.KWZER.001...,1449,NaN,https://s3.zoommer.ge/site/bb3d7c79-8a0c-437b-...,https://zoommer.ge/laptops/acer-aspire-lite-16...

In [101]:
df_cl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           253 non-null    object
 1   price          253 non-null    int64
 2   previousPrice  127 non-null    float64
 3   imageUrl       253 non-null    object
 4   route          253 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 10.0+ KB

In [104]:
df_cl.loc[:, 'price'] = df_cl['price'].astype(float)

In [117]:
df_cl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 253 entries, 0 to 252
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           253 non-null    object
 1   current_price  253 non-null    float64
 2   old_price      127 non-null    float64
 3   images         253 non-null    object
 4   product_url    253 non-null    object
 5   update_date    253 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), object(3)
memory usage: 13.8+ KB

In [111]:
df_cl = df_cl.rename(columns={'price': 'current_price', 'previousPrice': 'old_price', 'imageUrl': 'images', 'route': 'product_url'})

In [112]:
df_cl.columns

Index(['name', 'current_price', 'old_price', 'images', 'product_url'], dtype='object')

In [113]:
df_cl['update_date'] = datetime.now()

In [115]:
df_cl.head()

,name,current_price,old_price,images,product_url,update_date
0,Apple MacBook Air 13 inch 2022 MC7U4LL/A M2 Ch...,2999.0,NaN,https://s3.zoommer.ge/zoommer-images/thumbs/01...,https://zoommer.ge/laptops/apple-macbook-air-1...,2025-03-08 20:36:24.782906
1,Apple MacBook Air 13 inch 2022 MLXW3LL/A M2 Ch...,2599.0,3099.0,https://s3.zoommer.ge/zoommer-images/thumbs/01...,https://zoommer.ge/laptops/apple-macbook-air-1...,2025-03-08 20:36:24.782906
2,Apple MacBook Air 13 inch 2022 MC7X4B/A M2 Chi...,2999.0,NaN,https://s3.zoommer.ge/site/d79643b0-717a-4d86-...,https://zoommer.ge/laptops/apple-macbook-air-1...,2025-03-08 20:36:24.782906
3,Apple MacBook Air 13 inch 2022 MC7U4B/A M2 Chi...,2999.0,NaN,https://s3.zoommer.ge/site/3cc82a2e-5c27-467d-...,https://zoommer.ge/laptops/apple-macbook-air-1...,2025-03-08 20:36:24.782906
4,Acer Aspire Lite 16 AL16-51P-570D NX.KWZER.001...,1449.0,NaN,https://s3.zoommer.ge/site/bb3d7c79-8a0c-437b-...,https://zoommer.ge/laptops/acer-aspire-lite-16...,2025-03-08 20:36:24.782906

In [129]:
def get_response_data(cat_id):
    resp = requests.get(f'https://api.zoommer.ge/v1/Products/v3?CategoryId={cat_id}&Limit={random.randint(3422, 6543)}')
    resp = resp.json()
    df = pd.DataFrame(resp['products'])
    return df

In [130]:
def clean_data(df):
    df_cl = df[['name', 'price', 'previousPrice', 'imageUrl', 'route']]
    df_cl.loc[:, 'route'] = df_cl['route'].apply(lambda x: f'https://zoommer.ge/{x}')
    df_cl.loc[:, 'price'] = df_cl['price'].astype(float) 
    df_cl = df_cl.rename(columns={'price': 'current_price', 'previousPrice': 'old_price', 'imageUrl': 'images', 'route': 'product_url'})
    df_cl['update_date'] = datetime.now()
    return df_cl

In [131]:
engine = create_engine(database_url)
def export_data(df, db_name):
    df.to_sql(db_name, con=engine, if_exists='append', index=True)

In [134]:
for main_cat, sub_cat, cat_id in categories_cleaned:
    try:
        db_name = f'{sub_cat}_zoom'
        df = get_response_data(cat_id)
        df = clean_data(df)
        export_data(df, db_name)
        print(f'Successfully exported data of {sub_cat}: {main_cat}: {cat_id}.')
    except Exception as e:
        print(f'\nError occured on {sub_cat}: {main_cat}: {cat_id} - {e}\n')

Successfully exported data of mobile_brands: mobile_phones: 855.
Successfully exported data of headsets_buds: mobile_phones: 887.
Successfully exported data of smart_watch: mobile_phones: 873.
Successfully exported data of accessories_for_mobile: mobile_phones: 538.
Successfully exported data of tabs: tabs: 877.
Successfully exported data of smart_keyboard_pen: tabs: 1088.
Successfully exported data of graphics_drawing_tablet: tabs: 776.
Successfully exported data of e_book: tabs: 1086.
Successfully exported data of tab_accessories: tabs: 539.
Successfully exported data of headphones: tabs: 533.
Successfully exported data of cables: tabs: 1145.
Successfully exported data of brands: it_laptops: 717.
Successfully exported data of type: it_laptops: 531.
Successfully exported data of memory_carriers: it_laptops: 519.
Successfully exported data of accessories: it_laptops: 700.
Successfully exported data of office_equipment: it_laptops: 460.
Successfully exported data of projectors: it_laptops: 642.
Successfully exported data of living_room: smart_gadgets: 501.
Successfully exported data of home_care: smart_gadgets: 500.
Successfully exported data of kitchen: smart_gadgets: 495.
Successfully exported data of self_care: smart_gadgets: 490.
Successfully exported data of monitoring: smart_gadgets: 488.
Successfully exported data of smart_relocation: smart_gadgets: 1164.
Successfully exported data of outdoor: smart_gadgets: 1156.
Successfully exported data of sport: smart_gadgets: 1169.
Successfully exported data of pets: smart_gadgets: 469.
Successfully exported data of smart_lighting: smart_gadgets: 1178.
Successfully exported data of tools: smart_gadgets: 473.
Successfully exported data of audio_systems_brands: audio_systems: 528.
Successfully exported data of acoustic_systems: audio_systems: 532.
Successfully exported data of top_audio: audio_systems: 740.
Successfully exported data of microphones: audio_systems: 862.
Successfully exported data of playstation: gaming: 688.
Successfully exported data of xbox: gaming: 683.
Successfully exported data of nintendo: gaming: 927.
Successfully exported data of other_consoles: gaming: 1027.
Successfully exported data of gaming_laptops: gaming: 675.
Successfully exported data of gaming_accessories: gaming: 893.
Successfully exported data of gaming_monitors: gaming: 1140.
Successfully exported data of tvs: tv_monitors: 505.

Error occured on all_in_one: tv_monitors: 706 - "None of [Index(['name', 'price', 'previousPrice', 'imageUrl', 'route'], dtype='object')] are in the [columns]"

Successfully exported data of monitors: tv_monitors: 503.
Successfully exported data of tv_monitors_accessories: tv_monitors: 506.
Successfully exported data of media_players: tv_monitors: 891.
Successfully exported data of photography: photo_video: 858.
Successfully exported data of optics: photo_video: 462.
Successfully exported data of photo_video_accessories: photo_video: 732.
Successfully exported data of drones: photo_video: 865.
Successfully exported data of action_cameras: photo_video: 864.
Successfully exported data of photo_printers: photo_video: 881.
Successfully exported data of smartphone_photography: photo_video: 1151.